<section class="list-wrapper list-style ">
    <table id="list_ad" class="table table-striped table-responsive list-style">
        <thead>
        <tr class="tr-style">
            <td>广告标语</td>
            <td>企业名称</td>
            <td>开播时间</td>
            <td>停播时间</td>
            <td>操作</td>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="list in slideList">
            <td>{{list.content}}</td>
            <td>{{list.company}}</td>
            <td>{{list.start_time}}</td>
            <td>{{list.stop_time}}</td>
            <td>
                <span class="edit-color" data-toggle="modal" data-target="#view_ad" ng-click="view($index)">查看</span>
                <span ng-click="update($index)" class="edit-color" data-toggle="modal" data-target="#edit_ad">修改</span>
                <i class="fa fa-close delete-style" ng-click="delete($index)"></i>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="page-box add-page-box-margin">
        <div class="page-search-box">
            <ul>
                <li class="page-common" ng-click="previousPage()">上一页</li>
                <li class="page-common" ng-click="nextPage()">下一页</li>
            </ul>
        </div>
        <div>
            <input class="page-text" type="text" ng-model="page">
            <span class="go-page-common page-margin" ng-click="goPageList()">GO</span>
            <span class="total-color page-margin">当前页:{{currentPage}}</span>
            <span class="total-color">共{{totalPage}}页</span>
        </div>
    </div>
    <div class="modal fade " id="view_ad" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body"><img id="view_img" ng-src="{{slideList[viewId].image}}" alt="广告图"></div>
                <div class="modal-footer">
                    <button type="button" class="button button-primary button-rounded" data-dismiss="modal">关闭
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="edit_ad" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="form-group">
                        <label>广告标语</label>
                        <input type="text" class="form-control" ng-model="adMsg.content">
                    </div>
                    <div class="form-group">
                        <label>企业名称</label>
                        <input type="text" class="form-control" ng-model="adMsg.company">
                    </div>
                    <div class="form-group">
                        <label>开播时间</label>
                        <input class="datainp wicon" id="start_time" type="text" value="" placeholder="YYYY-MM-DD hh:mm:ss" readonly/>
                    </div>
                    <div class="form-group">
                        <label>停播时间</label>
                        <input class="datainp wicon" id="stop_time" type="text" value="" placeholder="YYYY-MM-DD hh:mm:ss" readonly/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                    </button>
                    <button type="button" class="btn btn-primary" ng-click="submitAd()">提交更改</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal -->
    </div>
    <div id="confirm_modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-body">确定删除该广告吗？</div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary" ng-click="confirmFn()">确定</button>
                </div>
            </div>
        </div>
    </div>
</section>