<section class="list-wrapper list-style ">
    <table id="list_company" class="table table-striped table-responsive list-style">
        <thead>
        <tr class="tr-style">
            <td>企业名称</td>
            <td>所在地址</td>
            <td>联系电话</td>
            <td>操作</td>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="list in companyList">
            <td>{{list.name}}</td>
            <td>{{list.address}}</td>
            <td>{{list.telephone}}</td>
            <td><span class="edit-color" ng-click="update($index)" data-toggle="modal" data-target="#edit_company">修改</span><i class="fa fa-close delete-style" ng-click="delete($index)"></i></td>
        </tr>
        </tbody>
    </table>
    <div class="page-box add-page-box-margin">
        <div class="page-search-box">
            <ul>
                <li class="page-common" ng-click="previousPage()">上一页</li>
                <li class="page-common" ng-click="nextPage()">下一页</li>
            </ul>
            <div class="list-search"><input type="text" ng-model="keywords" placeholder="按名称搜索"/><i class="fa fa-search" ng-click="search()"></i></div>
        </div>
        <div>
            <input class="page-text" type="text" ng-model="page">
            <span class="go-page-common page-margin" ng-click="goPageList()">GO</span>
            <span class="total-color page-margin">当前页:{{currentPage}}</span>
            <span class="total-color">共{{totalPage}}页</span>
        </div>
    </div>
    <!--    模态框-->
    <div>
        <div class="modal fade" id="edit_company" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="form-group add-div-margin">
                            <span>公司名称</span>
                            <input type="text" class="form-control" ng-model="companyMsg.name">
                        </div>
                        <div class="form-group add-div-margin">
                            <span>所在地址</span>
                            <input type="text" class="form-control" ng-model="companyMsg.address">
                        </div>
                        <div class="form-group add-div-margin">
                            <span>联系电话</span>
                            <input type="text" class="form-control" ng-model="companyMsg.telephone">
                        </div>
                        <div class="form-group add-div-margin">
                            <span>公司简介</span><span>20/200</span>
                            <textarea rows="10" class="form-control" ng-model="companyMsg.introduction"></textarea>
                        </div
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="button" class="btn btn-primary" ng-click="submitCompany()">提交更改</button>
                    </div>
                </div><!-- /.modal-content -->
            </div>
        </div><!-- /.modal -->
    </div>
    <div>
        <div id="confirm_modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-body">确定删除该用户吗？</div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <button type="button" class="btn btn-primary" ng-click="confirmFn()">确定</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>