<section id="company_d_wrapper">
    <div class="search-box">
        <input class="form-control" type="text" placeholder="请输入公司名称或关键字"/>
        <div class="button button-rounded button-primary">
            <i class="fa fa-search"></i>
        </div>
    </div>
    <img id="load_img" src="assets/images/loading.gif" alt="出错了">
    <!--            <div class="jumbotron">-->
    <!--                <p class="title-text">北京斯托盒中发送到发动机看见分列式公司</p>-->
    <!--                <p><span class="title-text">联系电话：</span><span class="main-text">027-8888888</span></p>-->
    <!--                <p><span class="title-text">地址：</span><span class="main-text">湖北省武汉市洪山区光谷软件园A1栋</span></p>-->
    <!--                <p><span class="title-text">公司简介：</span><span class="main-text">啊范德萨发大放到数据库简历库近距离坚决反对就啃hjsiajdlkckai新房去微软仍然声卡不行么想奋斗的卡卡haflsaflkdsjlksd法大师傅撒oijvovmml啊范德萨发大放到lksd法大师傅撒oijvovmml啊范德萨发大放到数据库简历库近距离坚决反对就啃hjsiajdlkckai新房去微软仍然声卡不行么想奋斗的卡卡haflsaflkdsjlksd法大师傅撒oijvovmml啊范德萨发大放到数据库简历库近距离坚决反对就啃hjsiajdlkckai新房去微软仍然声卡不行么想奋斗的卡卡haflsaflkdsjlksd法大师傅撒oijvovmml啊范德萨发大放到数据库l微软仍然声卡不行么想奋斗的卡卡haflsaflkdsjlksd法大师傅撒oijvovmml啊范德萨发大放到数据库简历库近距离坚决反对就啃hjsiajdlkckai新房去微软仍然声卡不行么想奋斗的卡卡haflsaflkdsjlksd法大师傅撒oijvovmml啊范德萨发大放到数据库微软仍然声卡不行么想</span></p>-->
    <!--            </div>-->
</section>