<section id="company_d_wrapper">
    <div class="search-box">
        <input class="form-control" type="text" placeholder="请输入公司名称或关键字" ng-model="companyName" ng-focus="closeArea()"/>
        <div class="button button-rounded button-primary" ng-click="findCompany()">
            <i class="fa fa-search"></i>
        </div>
    </div>
    <img id="load_img" src="assets/images/loading.gif" alt="出错了" ng-show="companyMsg == ''">
    <section ng-show="companyMsg != ''">
        <div class="panel panel-primary">
            <div class="panel-heading">搜索结果</div>
            <table class="table">
                <tr ng-repeat="list in companyMsg">
                    <td>{{list.name}}</td>
                    <td><span ng-click="showDetail($index)">查看</span></td>
                </tr>
            </table>
        </div>
        <div class="jumbotron" ng-show="showCompany">
            <p class="title-text">公司名称：{{detailMsg.name}}</p>
            <p><span class="title-text">联系电话：</span><span class="main-text">{{detailMsg.telephone}}</span></p>
            <p><span class="title-text">地址：</span><span class="main-text">{{detailMsg.address}}</span></p>
            <p><span class="title-text">公司简介：</span><span class="main-text">{{detailMsg.introduction}}</span></p>
        </div>
    </section>
</section>