<section id="slide_wrapper">
    <form>
        <div class="row">
            <div class="form-group add-div-margin col-lg-6">
                <label>广告标语</label>
                <input type="text" class="form-control" ng-model="adMsg.content"/>
            </div>
            <div class="form-group add-div-margin col-lg-6">
                <label>开播时间</label>
                <input class="datainp wicon" id="start_time" type="text" placeholder="YYYY-MM-DD hh:mm:ss" readonly/>
            </div>
        </div>
        <div class="row">
            <div class="form-group add-div-margin col-lg-6">
                <label>公司名称</label>
                <input type="text" class="form-control" ng-model="adMsg.company"/>
            </div>
            <div class="form-group add-div-margin col-lg-6">
                <label>停播时间</label>
                <input class="datainp wicon" id="stop_time" type="text" placeholder="YYYY-MM-DD hh:mm:ss" readonly/>
            </div>
        </div>
        <div class="row">
            <div class="form-group add-div-margin col-lg-6">
                <label>图片</label>
                <input type="file" class="filestyle" data-placeholder="当前未选择任何文件" data-buttonText="选择图片"/>
            </div>
            <div class="form-group add-div-margin col-lg-6">
                <div class="button button-primary button-rounded button-margin pull-right" ng-click="submitAd()">提交</div>
            </div>
        </div>
    </form>
</section>
