<section id="user_s_wrapper">
    <form>
        <div class="input-group">
            <span class="input-group-addon">用户名</span>
            <input type="text" class="form-control" ng-model="userMsg.name">
        </div>
        <div class="input-group">
            <span class="input-group-addon">密&nbsp;&nbsp;&nbsp;码</span>
            <input type="password" class="form-control" ng-model="userMsg.password">
        </div>
        <div class="input-group">
            <span class="input-group-addon">备&nbsp;&nbsp;&nbsp;注</span>
            <input type="text" class="form-control" ng-model="userMsg.remarks">
        </div>
    </form>
    <div class="button button-block button-primary button-rounded" ng-click="submitUser()">提交</div>
</section>
