<section id="edit_notice_wrapper">
    <form id="">
        <div class="form-group">
            <label>标题</label>
            <input type="text" class="form-control" ng-model="noticeMsg.title">
        </div>
        <div class="form-group">
            <label>内容</label>
            <textarea class="form-control" rows="5" ng-model="noticeMsg.content"></textarea>
        </div>
    </form>
    <div class="button button-block button-rounded button-primary button-margin" ng-click="addNotice()">提交</div>
</section>