<section id="company_wrapper">
    <form>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="form-group add-div-margin">
                <span>公司名称</span>
                <input type="text" class="form-control" ng-model="companyMsg.name">
            </div>
            <div class="form-group add-div-margin">
                <span>所在地址</span>
                <input type="text" class="form-control" ng-model="companyMsg.address">
            </div>
            <div class="form-group add-div-margin">
                <span>联系电话</span>
                <input type="text" class="form-control" ng-model="companyMsg.telephone">
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="form-group add-div-margin">
                <textarea rows="10" class="form-control" ng-model="companyMsg.introduction"></textarea>
            </div>
            <div class="button button-primary button-rounded button-margin pull-right" ng-click="submitCompany()">提交</div>
        </div>
    </form>
</section>