<section id="user_c_wrapper">
    <form>
        <?php if (isset($editUserId)): ?>
            <input type="hidden" class="form-control" ng-init="userMsgr.id = <?= $userId ?>" ng-model="userMsg.id"/>
        <?php else: ?>
            <input type="hidden" class="form-control" ng-init="userMsgr.id = 0" ng-model="userMsg.id"/>
        <?php endif; ?>
        <div class="input-group add-div-margin">
            <span class="input-group-addon">用户名</span>
            <input type="text" class="form-control" ng-model="userMsg.name"/>
        </div>
        <div class="input-group add-div-margin">
            <span class="input-group-addon">密&nbsp;&nbsp;&nbsp;码</span>
            <input type="password" class="form-control" ng-model="userMsg.password"/>
        </div>
        <div class="input-group add-div-margin">
            <span class="input-group-addon">手机号</span>
            <input type="text" class="form-control" ng-model="userMsg.phone"/>
        </div>
        <?php if ($_SESSION['power'] == 3): ?>
            <div class="input-group add-div-margin">
                <span class="input-group-addon">所属公司</span>
                <input type="text" class="form-control" ng-model="userMsg.company"/>
            </div>
        <?php endif; ?>
        <select class="form-control add-div-margin" ng-init="userMsg.role = roleMsg[0]" ng-model="userMsg.role" ng-options="role for role in roleMsg"></select>
    </form>
    <div class="button button-primary button-rounded button-margin pull-right" ng-click="submitUser()">提交</div>
    <div class="button button-royal button-rounded button-margin" ng-click="batchAdd()">
        <i class="fa fa-folder-open-o"></i>
        <span>批量添加</span>
    </div>
    <div class="form-group add-div-margin">
        <input type="file" class="filestyle" data-size="sm" data-placeholder="当前未选择任何文件" data-buttonText="选择文件"/>
    </div>
</section>
