<section id="user_s_wrapper">
    <form>
        <div class="error-tips alert alert-warning">
            <span><i class="fa fa-info-circle info-margin-right"></i>密码错误</span>
        </div>
        <div class="input-group">
            <span class="input-group-addon">用户名</span>
            <input type="text" class="form-control" placeholder="">
        </div>
        <div class="input-group">
            <span class="input-group-addon">密&nbsp;&nbsp;&nbsp;码</span>
            <input type="password" class="form-control" placeholder="">
        </div>
        <div class="input-group">
            <span class="input-group-addon">备&nbsp;&nbsp;&nbsp;注</span>
            <input type="text" class="form-control" placeholder="">
        </div>
    </form>
    <div class="button button-block button-primary button-rounded">提交</div>
    <div class="button button-block button-highlight button-rounded">重置</div>
</section>
