<section id="user_c_wrapper">
    <form>
        <div class="error-tips alert alert-warning">
            <span><i class="fa fa-info-circle info-margin-right"></i>密码错误</span>
        </div>
        <div class="input-group add-div-margin">
            <span class="input-group-addon">用户名</span>
            <input type="text" class="form-control" placeholder="">
        </div>
        <div class="input-group add-div-margin">
            <span class="input-group-addon">密&nbsp;&nbsp;&nbsp;码</span>
            <input type="password" class="form-control" placeholder="">
        </div>
        <div class="input-group add-div-margin">
            <span class="input-group-addon">手机号</span>
            <input type="text" class="form-control" placeholder="">
        </div>
        <div class="input-group add-div-margin">
            <span class="input-group-addon">所属公司</span>
            <input type="text" class="form-control" placeholder="">
        </div>
        <select name="" id="" class="form-control add-div-margin">
            <option value="">普通员工</option>
            <option value="">公司管理员</option>
        </select>
    </form>
    <div class="button button-primary button-rounded button-margin">提交</div>
    <div class="button button-royal button-rounded button-margin">
        <i class="fa fa-folder-open-o"></i>
        <span>批量添加</span>
    </div>
    <div class="button button-highlight button-rounded button-margin">重置</div>
</section>
