<section>
    <!--搜索框-->
    <div class="search-box">
        <input id="search-inp" type="text" placeholder="请输入快递运单" ng-model="code"/>
        <div class="search-icon" ng-click="findExpress(code)">
            <i class="fa fa-search"></i>
        </div>
    </div>
    <!--提示信息-->
<!--    <div id="search-info" class="error-tips alert alert-warning">-->
<!--        <span><i class="fa fa-info-circle info-margin-right"></i>请输入快递单号</span>-->
<!--    </div>-->
    <!--轮播图-->
    <div id="index_carousel" class="pic-box carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#index_carousel" data-slide-to="{{item}}" ng-class="{active : item == 0}"
                ng-repeat="item in cursor"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item" ng-class="{active : $index == 0}" ng-repeat="list in slideList">
                <img ng-src="{{list.image}}" alt="First slide">
                <div class="carousel-caption"><h4>{{list.content}}</h4></div>
            </div>
        </div>
    </div>
    <!--网站通知-->
    <ul class="info-box list-group">
        <li class="list-group-item active">重要通知<a id="more_url" href="#/notice_list" class="pull-right">more<i
                        class="fa fa-paper-plane"></i></a></li>
        <li ng-repeat="list in noticeList" class="list-group-item">{{list.title}}<span class="badge" data-toggle="modal"
                                                                                       ng-click="view($index)">查看</span>
        </li>
    </ul>
    <!-- 模态框-->
    <div class="modal fade " id="notice_index" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">{{noticeList[viewId].title}}</h5>
                </div>
                <div class="modal-body">{{noticeList[viewId].content}}</div>
                <div class="modal-footer">
                    <button type="button" class="button button-primary button-rounded" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
</section>