<section id="logistics_wrapper">
    <p class="remove-pad-lf">快递编号：<span>{{express[0].expressCode}}</span></p>
    <p class="remove-pad-lf">快递公司：<span>{{express[0].company}}</span></p>
    <ul>
        <li class="col-lg-3 col-md-3 col-sm-3 col-xs-3 remove-pad-lf">时间</li>
        <li class="col-lg-9 col-md-9 col-sm-9 col-xs-9"><i class="fa fa-truck"></i>站点</li>
    </ul>
    <table>
        <tr ng-repeat="list in express">
            <td class="col-lg-3 col-md-3 col-sm-3 col-xs-3 remove-pad-lf">{{list.time}}</td>
            <td class="col-lg-9 col-md-9 col-sm-9 col-xs-9 add-padding-lf"><i class="fa fa-circle transport"></i>{{list.site}}，{{list.username}}（{{list.phone}}），{{list.remarks}}</td>
        </tr>
    </table>
</section>