<section id="message_wrapper">
    <div class="panel panel-primary">
        <div class="panel-heading">您的消息列表</div>
        <table class="table">
            <tr>
                <td>2017-03-15 12:00:00</td>
                <td>系统消息<span class="badge">未读</span></td>
                <td class="view" data-toggle="modal" data-target="#message">查看<i class="fa fa-envelope-open-o"></i></td>
                <td><i class="fa fa-close delete-style"></i></td>
            </tr>
            <tr>
                <td>2017-03-15 12:00:00</td>
                <td>系统消息<span class="badge">未读</span></td>
                <td class="view" data-toggle="modal" data-target="#message">查看<i class="fa fa-envelope-open-o"></i></td>
                <td><i class="fa fa-close delete-style"></i></td>
            </tr>
            <tr>
                <td>2017-03-15 12:00:00</td>
                <td>系统消息<span class="badge">未读</span></td>
                <td class="view" data-toggle="modal" data-target="#message">查看<i class="fa fa-envelope-open-o"></i></td>
                <td><i class="fa fa-close delete-style"></i></td>
            </tr>
            <tr>
                <td>2017-03-15 12:00:00</td>
                <td>系统消息<span class="badge">未读</span></td>
                <td class="view" data-toggle="modal" data-target="#message">查看<i class="fa fa-envelope-open-o"></i></td>
                <td><i class="fa fa-close delete-style"></i></td>
            </tr>
            <tr>
                <td>2017-03-15 12:00:00</td>
                <td>系统消息<span class="badge">未读</span></td>
                <td class="view" data-toggle="modal" data-target="#message">查看<i class="fa fa-envelope-open-o"></i></td>
                <td><i class="fa fa-close delete-style"></i></td>
            </tr>
            <tr>
                <td>2017-03-15 12:00:00</td>
                <td>系统消息<span class="badge">未读</span></td>
                <td class="view" data-toggle="modal" data-target="#message">查看<i class="fa fa-envelope-open-o"></i></td>
                <td><i class="fa fa-close delete-style"></i></td>
            </tr>
            <tr>
                <td>2017-03-15 12:00:00</td>
                <td>系统消息<span class="badge">未读</span></td>
                <td class="view" data-toggle="modal" data-target="#message">查看<i class="fa fa-envelope-open-o"></i></td>
                <td><i class="fa fa-close delete-style"></i></td>
            </tr>
            <tr>
                <td>2017-03-15 12:00:00</td>
                <td>系统消息<span class="badge">未读</span></td>
                <td class="view" data-toggle="modal" data-target="#message">查看<i class="fa fa-envelope-open-o"></i></td>
                <td><i class="fa fa-close delete-style"></i></td>
            </tr>
        </table>
    </div>
    <nav aria-label="...">
        <ul class="pager">
            <li><a href="#">上一页</a></li>
            <li><a href="#">下一页</a></li>
        </ul>
    </nav>

    <!--modal(模态框)-->
    <div class="modal fade bs-example-modal-xm" id="message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">
                        系统消息
                    </h4>
                </div>
                <div class="modal-body">
                    您的快递在2017-03-14 12：19到达 杭州站
                </div>
                <div class="modal-footer">
                    <button type="button" class="button button-rounded button-primary" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
</section>