<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>在线快递服务平台</title>

    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/bootstrap.min.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/font-awesome.min.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/magic-check.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/button.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/ngDialog.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/ngDialog-theme-default.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/jedate.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/base.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/media.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/style.css">

    <script src="<?= base_url() ?>/assets/js/lib/jquery.min.js"></script>
    <script src="<?= base_url() ?>/assets/js/lib/bootstrap.min.js"></script>
    <script src="<?= base_url() ?>/assets/js/lib/angular.min.js"></script>
    <script src="<?= base_url() ?>/assets/js/lib/ngDialog.min.js"></script>
    <script src="<?= base_url() ?>/assets/js/lib/angular-route.min.js"></script>
    <script src="<?= base_url() ?>/assets/js/lib/bootstrap-filestyle.min.js"></script>
    <script src="<?= base_url() ?>/assets/js/lib/jquery.jedate.min.js"></script>

    <script src="<?= base_url() ?>/assets/js/boot.js"></script>
    <script src="<?= base_url() ?>/assets/js/home.js"></script>
    <script src="<?= base_url() ?>/assets/js/side.js"></script>
    <script src="<?= base_url() ?>/assets/js/main.js"></script>
</head>
<body>
<div class="container-fluid" ng-app="oesModule">
    <div ng-controller="home-controller">
        <header class="row navbar-fixed-top">
            <!--开启导航按钮-->
            <div id="bars"><i class="fa fa-bars"></i></div>
            <!--mini导航-->
            <div class="mini-nav">
                <ul>
                    <li><a href="#/home">首页</a></li>
                    <li><a href="#/send">寄快递</a></li>
                    <li><a href="#/company">快递公司查询</a></li>
                </ul>
            </div>

            <div class="head-nav col-md-8 col-lg-8">
                <div class="head-tab">
                    <span><i class="fa fa-leaf"></i></span>
                    <div ng-class="{selected:selectArr[0]}" ng-click="changeStyle(0)"><a href="#/home">首页</a></div>
                    <div ng-class="{selected:selectArr[1]}" ng-click="changeStyle(1)"><a href="#/send">寄快递</a></div>
                    <div ng-class="{selected:selectArr[2]}" ng-click="changeStyle(2)"><a href="#/company">快递公司查询</a></div>
                </div>
            </div>
            <div class="user-box col-md-4 col-lg-4">
                <div class="index-btn-group">
                    <?php if ($user != null): ?>
                        <a href="javascript:void(0)" ng-click="logOut()">退出</a>
                        <div class="welcome">
                            <span id="username" class="add-margin-right tooltip-test" ng-click="openNav()" data-toggle="tooltip" data-placement="bottom" title="点击显示导航"><i class="fa fa-user-circle add-margin-right"></i><?= $user['name'] ?></span>
                            <?php if ($num != 0 && $power == '1'): ?>
                                <span ng-click="goPage('#/message')"><i class="fa fa-bell-o"></i><?= $num ?></span>
                            <?php endif; ?>
                        </div>
                    <?php else: ?>
                        <a href="<?= base_url() ?>login">登录</a>
                        <a href="<?= base_url() ?>register">注册</a>
                    <?php endif; ?>
                </div>
            </div>
        </header>
        <!--左侧导航-->
        <?php if (isset($power)): ?>
        <section>
            <div class="side-bar" ng-class="{'show-nav':opened}">
                <i class="fa fa-close" ng-click="closeNav()"></i>
                <div ng-click="goPage('#/center')" class="first-menu"><i class="fa fa-user-o add-margin-right"></i><span>个人中心</span></div>
                <?php if ($power == 2 && $user['role'] == '企业管理员'): ?>
                    <div  ng-click="goPage('#/all_logistics')" class="first-menu"><i class="fa fa-user-o add-margin-right"></i><span>查看物流信息</span></div>
                    <div class="collapsed nav-header first-menu" data-toggle="collapse" data-target="#company_user">
                        <i class="fa fa-address-card-o add-margin-right"></i>
                        <span>企业用户管理</span>
                        <i class="fa fa-angle-double-down"></i>
                    </div>
                    <ul id="company_user" class="nav nav-list collapse second-menu">
                        <li ng-click="goPage('#/add_company_user')"><i class="fa fa-user-plus add-margin-right"></i>新增用户</li>
                        <li ng-click="goPage('#/company_user_list')"><i class="fa fa-list-alt add-margin-right"></i>用户列表</li>
                    </ul>
                <?php elseif ($power == 2 && $user['role'] == '普通员工'): ?>
                    <div ng-click="goPage('#/record')" class="first-menu"><i class="fa fa-user-o add-margin-right"></i><span>记录物流信息</span></div>
                    <div ng-click="goPage('#/personal_logistics')" class="first-menu"><i class="fa fa-user-o add-margin-right"></i><span>查看物流信息</span></div>
                <?php elseif ($power == 3): ?>
                    <div class="collapsed nav-header first-menu" data-toggle="collapse" data-target="#ordinary_user">
                        <i class="fa fa-address-book add-margin-right"></i>
                        <span>普通用户管理</span>
                        <i class="fa fa-angle-double-down"></i>
                    </div>
                    <ul id="ordinary_user" class="nav nav-list collapse second-menu">
                        <li ng-click="goPage('#/user_list')"><i class="fa fa-list-alt add-margin-right"></i>用户列表</li>
                    </ul>
                    <div  class="collapsed nav-header first-menu" data-toggle="collapse" data-target="#company">
                        <i class="fa fa-address-card-o add-margin-right"></i>
                        <span>企业管理</span>
                        <i class="fa fa-angle-double-down"></i>
                    </div>
                    <ul id="company" class="nav nav-list collapse second-menu">
                        <li ng-click="goPage('#add_company')"><i class="fa fa-home add-margin-right"></i>新增企业</a></li>
                        <li ng-click="goPage('#/company_list')"><i class="fa fa-home add-margin-right"></i>企业列表</li>
                        <li ng-click="goPage('#/add_company_user')"><i class="fa fa-user-plus add-margin-right"></i>新增企业用户</li>
                        <li ng-click="goPage('#/company_user_list')"><i class="fa fa-list-alt add-margin-right"></i>企业用户列表</li>
                    </ul>
                    <div class="collapsed nav-header first-menu" data-toggle="collapse" data-target="#system_user">
                        <i class="fa fa-users add-margin-right"></i>
                        <span>系统用户管理</span>
                        <i class="fa fa-angle-double-down"></i>
                    </div>
                    <ul id="system_user" class="nav nav-list collapse second-menu">
                        <li ng-click="goPage('#/add_system_user')"><i class="fa fa-user-plus add-margin-right"></i>新增管理员</li>
                        <li ng-click="goPage('#/list_system_user')"><i class="fa fa-list-alt add-margin-right"></i>管理员列表</li>
                    </ul>
                    <div class="collapsed nav-header first-menu" data-toggle="collapse" data-target="#notice">
                        <i class="fa fa-users add-margin-right"></i>
                        <span>公告管理</span>
                        <i class="fa fa-angle-double-down"></i>
                    </div>
                    <ul id="notice" class="nav nav-list collapse second-menu">
                        <li ng-click="goPage('#/add_notice')"><i class="fa fa-user-plus add-margin-right"></i>新增公告</li>
                        <li ng-click="goPage('#/notice_list')"><i class="fa fa-list-alt add-margin-right"></i>公告列表</li>
                    </ul>
                    <div class="collapsed nav-header first-menu" data-toggle="collapse" data-target="#ad">
                        <i class="fa fa-users add-margin-right"></i>
                        <span>广告管理</span>
                        <i class="fa fa-angle-double-down"></i>
                    </div>
                    <ul id="ad" class="nav nav-list collapse second-menu">
                        <li ng-click="goPage('#/add_ad')"><i class="fa fa-user-plus add-margin-right"></i>新增广告</li>
                        <li ng-click="goPage('#/ad_list')"><i class="fa fa-list-alt add-margin-right"></i>广告列表</li>
                    </ul>
                <?php endif; ?>
            </div>
        </section>
        <?php endif; ?>
    </div>

    <!--主体-->
    <div class="content row" ng-view></div>

    <!--底部-->
    <footer class="navbar-fixed-bottom">
        <div class="container-fluid">
            <p>Copyright &copy; 2017 Wuhan Polytechnic University IMIS DongHuating.&nbsp;All rights reserved</p>
        </div>
    </footer>
</div>
</body>
<script>
    $('[data-toggle="tooltip"]').tooltip();
</script>
</html>