<section id="center_wrapper">
    <form id="user_center">
        <div class="error-tips alert alert-warning">
            <span><i class="fa fa-info-circle info-margin-right"></i>密码错误</span>
        </div>
        <div class="input-group add-div-margin">
            <span class="input-group-addon change-default">用户名</span>
            <input type="text" class="form-control change-default" disabled>
        </div>
        <div class="input-group add-div-margin">
            <span class="input-group-addon change-default">密&nbsp;&nbsp;&nbsp;码</span>
            <input type="password" class="form-control change-default">
        </div>
        <div class="input-group add-div-margin">
            <span class="input-group-addon change-default">邮&nbsp;&nbsp;&nbsp;箱</span>
            <input type="email" class="form-control change-default">
        </div>
        <div class="input-group add-div-margin">
            <span class="input-group-addon change-default">手机号</span>
            <input type="text" class="form-control change-default">
        </div>
    </form>
    <div class="button button-block button-rounded button-primary button-margin">提交</div>
    <div class="button button-block button-rounded button-highlight button-margin-small">重置</div>
</section>
