<section class="list-wrapper list-style ">
    <table id="ls_express_personal" class="table table-striped table-responsive list-style">
        <thead>
        <tr class="tr-style">
            <td>快递单号 </td>
            <td>最新站点</td>
            <td>到站时间</td>
            <td>备注</td>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="list in expressList">
            <td>{{list.expressCode}}</td>
            <td>{{list.site}}</td>
            <td>{{list.time}}</td>
            <td>{{list.remarks}}</td>
        </tr>
        </tbody>
    </table>
    <div class="page-box add-page-box-margin">
        <ul>
            <li class="page-common" ng-click="previousPage()">上一页</li>
            <li class="page-common" ng-click="nextPage()">下一页</li>
        </ul>
        <div class="pull-right">
            <input class="page-text" type="text" ng-model="page">
            <span class="go-page-common page-margin" ng-click="goPageList()">GO</span>
            <span class="total-color page-margin">当前页:{{currentPage}}</span>
            <span class="total-color">共{{totalPage}}页</span>
        </div>
    </div>
</section>