<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/bootstrap.min.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/font-awesome.min.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/magic-check.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/button.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/ngDialog.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/lib/ngDialog-theme-default.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/base.css">
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/login_register.css">

    <script src="<?= base_url() ?>/assets/js/lib/jquery.min.js"></script>
    <script src="<?= base_url() ?>/assets/js/lib/bootstrap.min.js"></script>
    <script src="<?= base_url() ?>/assets/js/lib/angular.min.js"></script>
    <script src="<?= base_url() ?>/assets/js/lib/ngDialog.min.js"></script>


    <script src="<?= base_url() ?>/assets/js/boot.js"></script>
    <script src="<?= base_url() ?>/assets/js/login_register.js"></script>

    <title>注册</title>
</head>
<body class="login-register-bg" ng-app="loginModule">
<div class="login-register-wrapper" ng-controller="login-register-controller">
    <p id="register_title" class="title"><i class="fa fa-pencil"></i>注册新用户</p>
    <form id="register_form" class="login-register-common">
        <div>
            <i class="fa fa-user-o"></i>
            <input class="inp-box inp-common" type="text" name="name" placeholder="用户名" ng-model="userMsg.name" ng-focus="errorMsg.isHide = true"/>
        </div>
        <div>
            <i class="fa fa-key"></i>
            <input class="inp-box inp-common" type="password" name="password" placeholder="密码长度不低于6位" ng-model="userMsg.password" ng-focus="errorMsg.isHide = true"/>
        </div>
        <div>
            <i class="fa fa-mobile-phone"></i>
            <input class="inp-box inp-common" type="number" name="phone" placeholder="手机号" ng-model="userMsg.phone" ng-focus="errorMsg.isHide = true"/>
        </div>
        <div>
            <i class="fa fa-envelope-o"></i>
            <input class="inp-box inp-common" type="email" name="emai" placeholder="邮箱" ng-model="userMsg.email" ng-focus="errorMsg.isHide = true"/>
        </div>
    </form>
    <div id="register_btn" class="button button-block button-primary  btn-common" ng-click="register()">注册</div>
    <p class="error-msg bg-warning text-danger ng-hide" ng-hide="errorMsg.isHide"><i class="fa fa-warning"></i><span>{{errorMsg.text}}</span></p>
</div>
</body>
</html>