<section id="send_wapper" class="list-wrapper">
    <form>
        <div class="row">
            <div class="form-group col-lg-5 col-md-5 col-sm-5">
                <label>快递编号</label>
                <input type="text" class="form-control" placeholder=""/>
            </div>
            <div class="form-group col-lg-7 col-md-7 col-sm-7">
                <label>快递公司名称(全称)</label>
                <input type="text" class="form-control" placeholder=""/>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-5 col-md-5 col-sm-5">
                <label>收件人</label>
                <input type="text" class="form-control" placeholder=""/>
            </div>
            <div class="form-group col-lg-7 col-md-7 col-sm-7">
                <label>收件人联系方式</label>
                <input type="text" class="form-control" placeholder=""/>
            </div>
        </div>
        <div class="form-group">
            <label>收件地址</label>
            <input type="text" class="form-control" placeholder=""/>
        </div>
        <div class="row">
            <div class="form-group col-lg-5 col-md-5 col-sm-5">
                <label>寄件人</label>
                <input type="text" class="form-control" placeholder=""/>
            </div>
            <div class="form-group col-lg-7 col-md-7 col-sm-7">
                <label>寄件人联系方式</label>
                <input type="text" class="form-control" placeholder=""/>
            </div>
        </div>
        <div class="form-group">
            <label>寄件人地址</label>
            <input type="text" class="form-control" placeholder=""/>
        </div>
        <div class="form-group">
            <div class="button button-rounded button-primary">提交</div>
            <div class="button button-rounded button-highlight">重置</div>
        </div>
    </form>
</section>