<section class="list-wrapper list-style ">
    <table id="list_user_s" class="table table-striped table-responsive list-style">
        <thead>
        <tr class="tr-style">
            <td>用户名</td>
            <td>备注</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>动画听</td>
            <td>物流部经理</td>
        </tr>
        <tr>
            <td>忽悠为</td>
            <td>物流部经理</td>
        </tr>
        <tr>
            <td>东西南北</td>
            <td>物流部总经理</td>
        </tr>
        <tr>
            <td>哈哈哈</td>
            <td>物流部总经理</td>
        </tr>
        <tr>
            <td>慕容负性木木真</td>
            <td>物流部总经理</td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>物流部副总经理</td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>物流部副总经理</td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>物流部副总经理</td>
        </tr>
        </tbody>
    </table>
    <ul class="paging">
        <li class="page pull-left s-color direction">&laquo;</li>
        <li class="page s-color s-border pull-left">1</li>
        <li class="page s-color s-border pull-left">2</li>
        <li class="page s-color s-border pull-left cur-page-s">3</li>
        <li class="page s-color s-border pull-left">4</li>
        <li class="page s-color s-border pull-left">5</li>
        <li class="page pull-left s-color direction">&raquo;</li>
    </ul>
    <span class="s-color pull-right">共13页</span>
</section>