<section class="list-wrapper list-style ">
    <table id="list_user_c" class="table table-striped table-responsive ">
        <thead>
        <tr class="tr-style">
            <td>用户名</td>
            <td>手机号</td>
            <td>所属公司</td>
            <td>角色</td>
            <td>删除</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>湖北省武汉市北京斯托赫中科技有限公司</td>
            <td>普通员工</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>湖北省武汉市北京斯托赫中科技有限公司</td>
            <td>普通员工</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>湖北省武汉市北京斯托赫中科技有限公司</td>
            <td>公司管理员</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>湖北省武汉市北京斯托赫中科技有限公司</td>
            <td>普通员工</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>湖北省武汉市北京斯托赫中科技有限公司</td>
            <td>公司管理员</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>湖北省武汉市北京斯托赫中科技有限公司</td>
            <td>公司管理员</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>湖北省武汉市北京斯托赫中科技有限公司</td>
            <td>公司管理员</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>湖北省武汉市北京斯托赫中科技有限公司</td>
            <td>普通员工</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        </tbody>
    </table>
    <ul class="paging">
        <li class="page pull-left c-color direction">&laquo;</li>
        <li class="page c-color c-border pull-left">1</li>
        <li class="page c-color c-border pull-left">2</li>
        <li class="page c-color c-border pull-left cur-page-c">3</li>
        <li class="page c-color c-border pull-left">4</li>
        <li class="page c-color c-border pull-left">5</li>
        <li class="page pull-left c-color direction">&raquo;</li>
    </ul>
    <span class="c-color pull-right">共13页</span>
</section>