<section class="list-wrapper list-style ">
    <table id="list_user_o" class="table table-striped table-responsive list-style">
        <thead>
        <tr class="tr-style">
            <td>用户名</td>
            <td>手机号</td>
            <td>邮箱</td>
            <td>删除</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>donghuating@outlook.com</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>donghuating@outlook.com</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>donghuating@outlook.com</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>donghuating@outlook.com</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>donghuating@outlook.com</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>donghuating@outlook.com</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>donghuating@outlook.com</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td>13071292423</td>
            <td>donghuating@outlook.com</td>
            <td><i class="fa fa-close delete-style"></i></td>
        </tr>
        </tbody>
    </table>
    <ul class="paging">
        <li class="page pull-left o-color direction">&laquo;</li>
        <li class="page o-color o-border pull-left">1</li>
        <li class="page o-color o-border pull-left">2</li>
        <li class="page o-color o-border pull-left cur-page-o">3</li>
        <li class="page o-color o-border pull-left">4</li>
        <li class="page o-color o-border pull-left">5</li>
        <li class="page pull-left o-color direction">&raquo;</li>
    </ul>
    <span class="o-color pull-right">共13页</span>
</section>